CREATE TABLE games (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  players SMALLINT NOT NULL,
  icon VARCHAR DEFAULT NULL,
  link VARCHAR DEFAULT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);
